install:
  - cmd: git submodule -q update --init

environment:
  matrix:
    - QMAKE_SPEC : "win32-g++"
      CXX:   mingw53_32

configuration:
  - release

before_build:
  # Prepare the out-of-source build directory.
  - mkdir build
  - git submodule update --init --recursive
  - set Path=C:/Qt/Tools/mingw530_32/bin;%Path%
  - set CC=C:/Qt/Tools/mingw530_32/bin/gcc.exe
  - set CXX=C:/Qt/Tools/mingw530_32/bin/g++.exe
  - curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.65.1/windows/VulkanSDK-1.0.65.1-Installer.exe?Human=true
  - VulkanSDK.exe /S
  - set VK_SDK_PATH=C:/VulkanSDK/1.0.65.1

build_script:
  - cmake --version
  - gcc   --version
  - g++   --version
  - cmake -H. -Bbuild -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DBUILD_EXTRAS:BOOL=OFF" "-DCMAKE_BUILD_TYPE:STRING=Debug" "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/5.9.1/mingw53_32" "-DCMAKE_MAKE_PROGRAM:STRING=C:/Qt/mingw530_32/bin/mingw32-make.exe"
  - cmake --build ./build --target all

after_build:
  - echo gothic-win32-v%appveyor_build_version% >> VERSION
  - set name="bin/open_gothic.zip"
  - xcopy build/lib/MoltenTempest/bin/libMoltenTempest.dll bin/ /Y
  - xcopy C:/Qt/Tools/mingw530_32/bin/libgcc_s_dw2-1.dll   bin/ /Y
  - xcopy C:/Qt/Tools/mingw530_32/bin/libstdc++-6.dll      bin/ /Y
  - xcopy C:/Qt/Tools/mingw530_32/bin/libwinpthread-1.dll  bin/ /Y
  - 7z a %name%    VERSION
  - 7z a %name%    bin\shader\*.sprv
  - 7z a %name%    bin\data\*
  - 7z a %name% -r bin\*.exe
  - 7z a %name% -r bin\*.dll

artifacts:
  - path: bin/open_gothic.zip
    name: archive

deploy:
  release: gothic-win32-v$(appveyor_build_version)
  description: 'no release description'
  provider: GitHub
  auth_token:
    secure: YLdtUMsAcc8FUr3kgwhQW7nkl5jDpLKbelvzWzzTWUfAiDd92Kd15rjlDJVEEFzo
  artifact: archive
  draft: true
  force_update: true
  prerelease: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
